---

- hosts: all
  become: true
  pre_tasks:

  - name: Install Glance
    apt:
      name:
        - glance
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install keystone
    apt:
      name:
        - keystone
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install nova
    apt:
      name:
        - nova-compute
      state: latest
    when: ansible_distribution == "Ubuntu"
